[package]
name = "evalrus"
version = "0.0.1"
authors = ["Peter Liniker <peter.liniker+github@gmail.com>"]

[dependencies]
clap = "2.20.3"
rustyline = "1.0.0"
blockalloc = { git = "https://github.com/rust-hosted-langs/book/" }
